spring:
  profiles:
    active: dev
server:
  port: 8087
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-enums-package: cn.suray.wms.*.bean.enums
  configuration:
    local-cache-scope: statement #禁用一级缓存
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: ignored
      logic-delete-field: effective  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      columnFormat: '`%s`' # 默认mysql
    banner: false

logging:
  config: classpath:logback-spring.xml
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    #   数据源基本配置
    #    url: jdbc:sqlserver://192.168.1.106:1433;DatabaseName=ynj
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    username: sa
    #    password: suray2020.
    #    druid:
    #      transaction-query-timeout: 50
    url: jdbc:mysql://192.168.1.106:3306/wms?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'suray2020.'
  data:
    mongodb:
      host: 192.168.1.233
      port: 27017
      database: product1
      username: root
      password: suray2020.
      #uri:
      authentication-database: admin
feign:
  api: 'http://192.168.1.106:8080/wms-cli3.0'
  wcs: '192.168.1.106:8081'
  ats: '127.0.0.1:8080'
conf-path:
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    #   数据源基本配置
    url: jdbc:sqlserver://192.168.1.207:1433;DatabaseName=wms3.0
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: suray2020.
  data:
    mongodb:
      host: 192.168.1.233
      port: 27017
      database: product
      username: root
      password: suray2020.
      #uri:
      authentication-database: admin
feign:
  api: 192.168.1.230:8080/wms3.0
  wcs: 192.168.1.106:8081
  ats: 127.0.0.1:8080
conf-path:
---
spring:
  config:
    activate:
      on-profile: product
  datasource:
    #   数据源基本配置
    url: jdbc:sqlserver://192.168.1.106:1433;DatabaseName=wms3.0
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: wms3.0
    password: suray2021.
feign:
  api: 192.168.1.230:8080/wms3.0
  wcs: 192.168.1.106:8081
  ats: 127.0.0.1:8080
conf-path: 'C:\\conf.yml'


